version: "3.7"

services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
      POSTGRES_USER: postgres
    volumes:
      - ../postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  test_proxy:
    container_name: test_proxy
    restart: always
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    environment:
      CONF_PATH: "./conf.yml"
      APP_MODE: "dev"
    ports:
      - 8000:8000
    volumes:
      - "./conf.yml:/app/conf.yml"
    depends_on:
      - db
